"""Read-only CatalogLibrary core for ZeSolver."""

from .adoption import CatalogLibraryAdoptionPlan, canonical_provenance_fingerprint
from .atomic_adoption import CatalogLibraryAdoptionError, CatalogLibraryAdoptionWriter
from .adapters import blind4d_index_descriptors, near_source_descriptor
from .discovery import discover_existing
from .manifest import (
    CatalogCompatibilityError,
    CatalogCorruptionError,
    CatalogIncompleteError,
    CatalogLibrary,
    CatalogLibraryError,
    CatalogManifestError,
    CatalogMissingError,
    CatalogVersionError,
    load_manifest,
)
from .models import (
    Blind4DIndexDescriptor,
    CatalogCapabilities,
    CatalogCoverage,
    CatalogDataStatus,
    CatalogDiscoveryResult,
    CatalogIndex,
    CatalogIssue,
    CatalogLibraryAdoptionResult,
    CatalogLibraryAdoptionPlanResult,
    CatalogLibraryAdoptionTelemetry,
    CatalogManifest,
    CatalogRepairAction,
    CatalogSource,
    CatalogStatus,
    CatalogValidationReport,
    CatalogAdoptionCommitStatus,
    CatalogAdoptionWriteMode,
    CoverageStatus,
    FingerprintPolicy,
    IssueSeverity,
    LegacyIndexDescriptor,
    NearCatalogDescriptor,
)

__all__ = [
    "Blind4DIndexDescriptor",
    "CatalogCapabilities",
    "CatalogCompatibilityError",
    "CatalogCorruptionError",
    "CatalogCoverage",
    "CatalogDataStatus",
    "CatalogDiscoveryResult",
    "CatalogAdoptionCommitStatus",
    "CatalogAdoptionWriteMode",
    "CatalogIncompleteError",
    "CatalogIndex",
    "CatalogIssue",
    "CatalogLibraryAdoptionError",
    "CatalogLibraryAdoptionPlan",
    "CatalogLibraryAdoptionResult",
    "CatalogLibraryAdoptionPlanResult",
    "CatalogLibraryAdoptionTelemetry",
    "CatalogLibraryAdoptionWriter",
    "CatalogLibrary",
    "CatalogLibraryError",
    "CatalogManifest",
    "CatalogManifestError",
    "CatalogMissingError",
    "CatalogRepairAction",
    "CatalogSource",
    "CatalogStatus",
    "CatalogValidationReport",
    "CatalogVersionError",
    "CoverageStatus",
    "FingerprintPolicy",
    "IssueSeverity",
    "LegacyIndexDescriptor",
    "NearCatalogDescriptor",
    "blind4d_index_descriptors",
    "canonical_provenance_fingerprint",
    "discover_existing",
    "load_manifest",
    "near_source_descriptor",
]
